run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-rules:
    # Exclude tests from some strict checks
    - path: _test\.go
      linters:
        - errcheck
    # Exclude certain patterns
    - linters:
        - staticcheck
      text: "SA1019:"  # Ignore deprecation warnings for now
